### ISSUE TITLE
getIpOptions not found

### ISSUE THREAD

**Issue by moshanATucsd** [GilgameshD/Multiple-View-Car-Localization#2]
Where is getIpOptions function? Is this in matlab toolbox or a customized function?

**Comment by GilgameshD** [comment]
I am sorry that it seems to be a mistake. I have replaced that name with function and thanks a lot.
The only one toolbox I use is the Caltech Calibration Toolbox (http://www.vision.caltech.edu/bouguetj/calib_doc/)

**Comment by moshanATucsd** [comment]
Great, thanks!
